Make build compile on JDK 11 and remove JDK 8 guards.
Running the tests still fails due to an exception
```
[E] Caused by: java.lang.NoClassDefFoundError: javax/tools/ToolProvider
[E] 	at sbt.internal.inc.javac.JavaCompiler$.local(JavaCompiler.scala:68)
[E] 	at sbt.internal.inc.javac.JavaTools$.directOrFork(JavaCompiler.scala:55)
[E] 	at sbt.internal.inc.ZincUtil$.compilers(ZincUtil.scala:94)
[E] 	at bloop.CompilerCache.newCompilers(CompilerCache.scala:27)
```