[PLAT-146194]: fix NPE related to javac annotations (#153)
I don't have a reliable reproduction so I can't guarantee this diff
fixes the problem, but we were passing `null` to the
`annotationBuilder()` method so this should prevent it.

```
java.lang.NullPointerException: Cannot invoke "com.sun.source.util.TreePath.getLeaf()" because "path" is null
jdk.compiler/com.sun.tools.javac.api.JavacTrees.getElement(JavacTrees.java:411)
	jdk.compiler/com.sun.tools.javac.api.JavacTrees.getElement(JavacTrees.java:166)
	scala.meta.internal.semanticdb.javac.SemanticdbTrees.annotationBuilder(SemanticdbTrees.java:85)
	scala.meta.internal.semanticdb.javac.SemanticdbTrees.annotations(SemanticdbTrees.java:57)
```