Fixed a NullPointerException in Java AST parsing. (#8604)
The exception looked like this:

```
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "com.sun.source.tree.VariableTree.getType()" is null
```

---------

Co-authored-by: Patryk Zieliński <patrykzielinskiti@gmail.com>