bugfix: Always check if position is defined
Previously, we could get an exception:

```
java.lang.UnsupportedOperationException: Position.start on NoPosition
	at scala.reflect.internal.util.Position.fail(Position.scala:24)
	at scala.reflect.internal.util.UndefinedPosition.start(Position.scala:101)
	at scala.reflect.internal.util.UndefinedPosition.start(Position.scala:97)
	at scala.meta.internal.pc.SemanticTokenProvider.$anonfun$ord$1(SemanticTokenProvider.scala:41)
	at scala.meta.internal.pc.SemanticTokenProvider.$anonfun$ord$1$adapted(SemanticTokenProvider.scala:40)
	at scala.math.Ordering$$anon$4.compare(Ordering.scala:316)
	at scala.collection.immutable.RedBlackTree$.upd(RedBlackTree.scala:415)
	at scala.collection.immutable.RedBlackTree$.update(RedBlackTree.scala:175)
	at scala.collection.immutable.TreeSet.incl(TreeSet.scala:163)
	at scala.collection.immutable.TreeSet.incl(TreeSet.scala:39)
	at scala.collection.immutable.SetOps.$plus(Set.scala:46)
	at scala.collection.immutable.SetOps.$plus$(Set.scala:46)
	at scala.collection.immutable.AbstractSet.$plus(Set.scala:348)
```

Now, this should not happen since we always check if pos is defined.