Reference pluginCrossBuild via reflection to support older sbt 0.13.
The `pluginCrossBuild` setting came in 0.13.16, so currently users get a
compile error when opening older sbt builds on their machine as long as
they have used Metals in at least one sbt 0.13 build. After this commit,
users no longer get a compile error but they the following runtime exception
if they start `sbt` with the environment variable `METALS_ENABLED=true`.
```
[error] java.lang.NoSuchMethodError: sbt.Keys$.pluginCrossBuild()Lsbt/TaskKey;
```


Former-commit-id: 0f23c3c3c677a50d9e6c0e374b64d688d2eff792